baseurl = "https://00sapo.github.io"
# baseurl = "https://federicosimonetta.eu.org/"
#
publishDir = "./"
title = "Federico Simonetta"
defaultContentLanguage = "en"
theme = "sam"
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-142387081-1"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableRobotsTXT = true
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
    name = "Federico Simonetta"

[params]
    dateform = "Mon Jan 02, 2006"
    dateformfull = "Mon Jan 2 2006 15:04:05 EST"
    favicon = "/img/avatar.ico"
    homepage = "home" # What to call the home page link
    footerText = "_Fluid thoughts against categories_"

# Metadata for Open Graph and Twitter
    images = ["/img/image.jpg"]            # Image that shows on Twitter cards and Open Graph links to the site
    title = "Federico Simonetta"
    keywords = "Federico Simonetta, musica, informatica, music, computer science, pavia, padova, university, computer engineer, music composition, milan, research, phd"
    description = "Federico Simonetta is musician and computer engineer. From Pavia to Milan through Padua. Here you found my publications, music, software and contacts. Pop in to know me!"
        
    custom_css = ["css/custom.css"]

    [params.publisher]
        name = "Federico Simonetta"
        
        [params.publisher.logo]
            url = "/img/avatar.ico"
            width = 128
            height = 128

    [params.logo]
        url = "/img/avatar.ico"
        width = 128
        height = 128

    [params.image]
        url = "/img/avatar.png"
        width = 1075
        height = 531

    [[params.mainMenu]]
        link = "/about"
        text = "who am I?"

    [[params.mainMenu]]
        link = "/publications"
        text = "publications"

    [[params.mainMenu]]
        link = "/post"
        text = "random posts"

    [[params.mainMenu]]
        link = "/links"
        text = "not so random links"

    [[params.mainMenu]]
        link = "/software"
        text = "unsoftware"

    [[params.mainMenu]]
        link = "/music"
        text = "noisy stuffs"

    [[params.mainMenu]]
        link = "/teaching"
        text = "don't tell this anyone..."

    [[params.mainMenu]]
       link = "/notes/allnotes"
       text = "...tell everyone this one"

# [taxonomies]
#     tag = "tags"
#     category = ""  # Categories are disabled by default.

[imaging]
    quality = 75
